name: Update HA Version Badge

on:
  push:
    paths:
      - .HA_VERSION

jobs:
  badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read version
        id: get_version
        run: |
          echo "VERSION=$(cat .HA_VERSION)" >> $GITHUB_ENV

      - name: Build badge JSON
        run: |
          echo '{ "schemaVersion": 1, "label": "HA Version", "message": "'"${VERSION}"'", "color": "blue" }' > badge.json

      - name: Commit badge JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update HA version badge"
          file_pattern: badge.json
